config/routes.rb
Rails.application.routes.draw do

  resources :menus, only: [] do 
    resources :reservations, only: [:new, :create]
  end

  scope '/admin' do
    
    resources :meals do
      resources :comments
    end

    resources :menus do
      resources :reservations, only: [:index, :show, :destroy]
    end

    resources :alergens, :customers
  end

  resources :ratings

  get '/meals/:id', to: 'home#show', as: 'meal_view'
  get '/admin', to: 'admin#index'

  root 'home#index'
end

app/models/alergen.rb
class Alergen < ApplicationRecord
  validates :identifier, presence: true, uniqueness: true
  validates :name, presence: true

  has_and_belongs_to_many :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meal

  validates :commenter, :body, :email, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reservations
end

app/models/meal.rb
class Meal < ApplicationRecord
  enum kind: [ :appetizer, :soup, :main, :sweet ]
  
  validates :title, presence: true, uniqueness: true
  validates :kind, :price, presence: true

  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :alergens
  has_and_belongs_to_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :date, presence: true

  has_and_belongs_to_many :meals
  has_many :reservations
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :meal
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :menu
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/alergens_controller.rb
class AlergensController < ApplicationController
  def index
    @alergens = Alergen.all
  end

  def show
    @alergen = Alergen.find(params[:id])
  end

  def new
    @alergen = Alergen.new
  end

  def edit
    @alergen = Alergen.find(params[:id])
  end

  def create
    @alergen = Alergen.new(alergen_params)

    if @alergen.save
      redirect_to @alergen
    else
      render 'new'
    end
  end

  def update
    @alergen = Alergen.find(params[:id])

    if @alergen.update(alergen_params)
      redirect_to @alergen
    else
      render 'edit'
    end
  end

  def destroy
    @alergen = Alergen.find(params[:id])
    @alergen.destroy

    redirect_to alergens_path
  end

  private
    def alergen_params
      params.require(:alergen).permit(:name, :identifier)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.where('date >= ?', DateTime.now).order(:date)
  end

  def show
    @meal_view = Meal.find(params[:id])
    @rating_avg = Rating.where(meal_id: params[:id]).average(:value)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def create
    @meal = Meal.new(meal_params)
   
    if @meal.save
      params[:meal][:alergen_ids].each do |alergen_id|
        if !alergen_id.empty?
          @meal.alergens << Alergen.find(alergen_id)
        end
      end
      redirect_to @meal
    else
      render 'new'
    end
  end

  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      alergens = []
      params[:meal][:alergen_ids].each do |alergen_id|
        if !alergen_id.empty?
          alergens << Alergen.find(alergen_id)
        end
      end
      @meal.alergens = alergens
      redirect_to @meal
    else
      render 'edit'
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    redirect_to meals_path
  end

  private
    def meal_params
      params.require(:meal).permit(:title, :kind, :price)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      if !params[:menu][:appetizer_id].empty?
        @menu.meals << Meal.find(params[:menu][:appetizer_id])
      end
      if !params[:menu][:soup_id].empty?
        @menu.meals << Meal.find(params[:menu][:soup_id])
      end
      if !params[:menu][:main_id].empty?
        @menu.meals << Meal.find(params[:menu][:main_id])
      end
      if !params[:menu][:sweet_id].empty?
        @menu.meals << Meal.find(params[:menu][:sweet_id])
      end
      redirect_to @menu
    else
      render 'new'
    end
  end

  def update
    @menu = Menu.find(params[:id])

    if @menu.update(menu_params)
      redirect_to @menu
    else
      render 'edit'
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    redirect_to menus_path
  end

  private
    def menu_params
      params.require(:menu).permit(:date)
    end
end

app/helpers/alergens_helper.rb
module AlergensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alergens/_form.html.erb
<%= form_with model: @alergen, local: true do |form| %>
  <% if @alergen.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@alergen.errors.count, "error") %>
        prohibited this article from being saved:
      </h4>
      <ul>
        <% @alergen.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Name</label>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <label>Identifier</label>
    <%= form.number_field :identifier, in: 1..14, step: 1, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= link_to 'Back', alergens_path, :class => 'btn btn-warning' %>
    <%= form.submit 'Submit', :class => 'btn btn-primary float-right' %>
  </div>
<% end %>

app/views/alergens/edit.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Edit Allergen</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/alergens/index.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1 class="float-left">Listing allergens</h1>
      <%= link_to 'New allergen', new_alergen_path, :class => 'btn btn-primary float-right' %>
    </div>
    <div class="col-8">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Identified</th>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <% @alergens.each do |alergen| %>
          <tr>
            <td><%= alergen.identifier %></td>
            <td><%= alergen.name %></td>
            <td>
              <%= link_to 'Edit', edit_alergen_path(alergen), :class => 'btn btn-warning' %>
              <%= link_to 'Delete', alergen_path(alergen), :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/alergens/new.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>New Allergen</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/alergens/show.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>
        Allergen: <%= @alergen.name %>
      </h1>

      <p>
        <strong>Identifier:</strong>
        <%= @alergen.identifier %>
      </p>

      <%= link_to 'Back', alergens_path, :class => 'btn btn-warning' %>
    </div>
  </div>
</div>