config/routes.rb
Rails.application.routes.draw do

  resources :menus, only: [] do 
    resources :reservations, only: [:new, :create]
  end

  scope '/admin' do
    
    resources :meals do
      resources :comments
    end

    resources :menus do
      resources :reservations, only: [:index, :show, :destroy]
    end

    resources :alergens, :customers
  end

  resources :ratings

  get '/meals/:id', to: 'home#show', as: 'meal_view'
  get '/admin', to: 'admin#index'

  root 'home#index'
end

app/models/alergen.rb
class Alergen < ApplicationRecord
  validates :identifier, presence: true, uniqueness: true
  validates :name, presence: true

  has_and_belongs_to_many :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meal

  validates :commenter, :body, :email, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reservations
end

app/models/meal.rb
class Meal < ApplicationRecord
  enum kind: [ :appetizer, :soup, :main, :sweet ]
  
  validates :title, presence: true, uniqueness: true
  validates :kind, :price, presence: true

  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :alergens
  has_and_belongs_to_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :date, presence: true

  has_and_belongs_to_many :meals
  has_many :reservations
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :meal
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :menu
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.where('date >= ?', DateTime.now).order(:date)
  end

  def show
    @meal_view = Meal.find(params[:id])
    @rating_avg = Rating.where(meal_id: params[:id]).average(:value)
  end
end

app/helpers/alergens_helper.rb
module AlergensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/_nav.html.erb
<div class="container" style="margin-bottom: 30px;">
  <div class="row">
    <div class="col-12">
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <%= link_to 'Allergens', alergens_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Customers', customers_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Daily Menus', menus_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Meals', meals_path, :class => 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily menu reservations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>