config/routes.rb
Rails.application.routes.draw do

  resources :menus, only: [] do 
    resources :reservations, only: [:new, :create]
  end

  scope '/admin' do
    
    resources :meals do
      resources :comments
    end

    resources :menus do
      resources :reservations, only: [:index, :show, :destroy]
    end

    resources :alergens, :customers
  end

  resources :ratings

  get '/meals/:id', to: 'home#show', as: 'meal_view'
  get '/admin', to: 'admin#index'

  root 'home#index'
end

app/models/alergen.rb
class Alergen < ApplicationRecord
  validates :identifier, presence: true, uniqueness: true
  validates :name, presence: true

  has_and_belongs_to_many :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meal

  validates :commenter, :body, :email, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reservations
end

app/models/meal.rb
class Meal < ApplicationRecord
  enum kind: [ :appetizer, :soup, :main, :sweet ]
  
  validates :title, presence: true, uniqueness: true
  validates :kind, :price, presence: true

  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :alergens
  has_and_belongs_to_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :date, presence: true

  has_and_belongs_to_many :meals
  has_many :reservations
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :meal
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :menu
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.where('date >= ?', DateTime.now).order(:date)
  end

  def show
    @meal_view = Meal.find(params[:id])
    @rating_avg = Rating.where(meal_id: params[:id]).average(:value)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def create
    @meal = Meal.new(meal_params)
   
    if @meal.save
      params[:meal][:alergen_ids].each do |alergen_id|
        if !alergen_id.empty?
          @meal.alergens << Alergen.find(alergen_id)
        end
      end
      redirect_to @meal
    else
      render 'new'
    end
  end

  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      alergens = []
      params[:meal][:alergen_ids].each do |alergen_id|
        if !alergen_id.empty?
          alergens << Alergen.find(alergen_id)
        end
      end
      @meal.alergens = alergens
      redirect_to @meal
    else
      render 'edit'
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    redirect_to meals_path
  end

  private
    def meal_params
      params.require(:meal).permit(:title, :kind, :price)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      if !params[:menu][:appetizer_id].empty?
        @menu.meals << Meal.find(params[:menu][:appetizer_id])
      end
      if !params[:menu][:soup_id].empty?
        @menu.meals << Meal.find(params[:menu][:soup_id])
      end
      if !params[:menu][:main_id].empty?
        @menu.meals << Meal.find(params[:menu][:main_id])
      end
      if !params[:menu][:sweet_id].empty?
        @menu.meals << Meal.find(params[:menu][:sweet_id])
      end
      redirect_to @menu
    else
      render 'new'
    end
  end

  def update
    @menu = Menu.find(params[:id])

    if @menu.update(menu_params)
      redirect_to @menu
    else
      render 'edit'
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    redirect_to menus_path
  end

  private
    def menu_params
      params.require(:menu).permit(:date)
    end
end

app/helpers/alergens_helper.rb
module AlergensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="float-left">Restaurant daily menu reservation system</h1>
    </div>
    <div class="col-12">
      <div class="row">
        <% @menus.each_with_index do |menu, index| %>
          <% if (index % 3 == 0) %>
            <div class="clearfix"></div>
          <% end %>
          <div class="col-4">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">
                  <%= menu.date.strftime("%A, %e %b") %>
                </h4>

                <ul>
                  <li>
                    <strong>Appetizer:</strong>
                    <% menu.meals.each do |meal| %>
                      <% if meal.kind == 'appetizer' %>
                        <%= link_to meal.title, meal_view_path(meal) %>
                      <% end %>
                    <% end %>
                  </li>

                  <li>
                    <strong>Soup:</strong>
                    <% menu.meals.each do |meal| %>
                      <% if meal.kind == 'soup' %>
                        <%= link_to meal.title, meal_view_path(meal) %>
                      <% end %>
                    <% end %>
                  </li>

                  <li>
                    <strong>Main meal:</strong>
                    <% menu.meals.each do |meal| %>
                      <% if meal.kind == 'main' %>
                        <%= link_to meal.title, meal_view_path(meal) %>
                      <% end %>
                    <% end %>
                  </li>

                  <li>
                    <strong>Sweet:</strong>
                    <% menu.meals.each do |meal| %>
                      <% if meal.kind == 'sweet' %>
                        <%= link_to meal.title, meal_view_path(meal) %>
                      <% end %>
                    <% end %>
                  </li>
                </ul>

                
                <%= link_to 'Reservation', new_menu_reservation_path(menu.id), :class => 'btn btn-success mx-auto center-button' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>
        Meal: <%= @meal_view.title %>
      </h1>

      <p>
        <strong>Type:</strong>
        <% if @meal_view.kind == 'main' %>
          main dish
        <% else %>
          <%= @meal_view.kind %>
        <% end %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @meal_view.price %>
      </p>

      <p>
        <strong>Allergens:</strong>
        <%= @meal_view.alergens.map(&:name).join(', ') %>
      </p>

      <p>
        <strong>Average customers rating:</strong>
        <%= @rating_avg %>
      </p>

      <h3>Rate our food!</h3>
      <p>
        <a href="#" onclick="vote(<%= @meal_view.id %>, 1)"><%= fa_icon "star" %></a>
        <a href="#" onclick="vote(<%= @meal_view.id %>, 2)"><%= fa_icon "star" %></a>
        <a href="#" onclick="vote(<%= @meal_view.id %>, 3)"><%= fa_icon "star" %></a>
        <a href="#" onclick="vote(<%= @meal_view.id %>, 4)"><%= fa_icon "star" %></a>
        <a href="#" onclick="vote(<%= @meal_view.id %>, 5)"><%= fa_icon "star" %></a>
      </p>

      <h3>Add a comment:</h2>
      <%= form_with(model: [ @meal_view, @meal_view.comments.build ], local: true) do |form| %>
        <div class="form-group">
          <label>Commenter</label>
          <%= form.text_field :commenter, :class => 'form-control' %>
        </div>
        
        <div class="form-group">
          <label>Email</label>
          <%= form.text_field :email, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <label>Text</label>
          <%= form.text_area :body, :class => 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= link_to 'Back', root_path, :class => 'btn btn-warning' %>
          <%= form.submit 'Submit', :class => 'btn btn-primary float-right' %>
        </div>
      <% end %>

    </div>

    <div class="col-4">
      <h2>Comments</h2>
      <% @meal_view.comments.each do |comment| %>
        <% if comment.commenter != nil %>
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">
                <%= comment.commenter %>
              </h4>
              <p>
                <%= comment.body %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>