config/routes.rb
Rails.application.routes.draw do

  resources :menus, only: [] do 
    resources :reservations, only: [:new, :create]
  end

  scope '/admin' do
    
    resources :meals do
      resources :comments
    end

    resources :menus do
      resources :reservations, only: [:index, :show, :destroy]
    end

    resources :alergens, :customers
  end

  resources :ratings

  get '/meals/:id', to: 'home#show', as: 'meal_view'
  get '/admin', to: 'admin#index'

  root 'home#index'
end

app/models/alergen.rb
class Alergen < ApplicationRecord
  validates :identifier, presence: true, uniqueness: true
  validates :name, presence: true

  has_and_belongs_to_many :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meal

  validates :commenter, :body, :email, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reservations
end

app/models/meal.rb
class Meal < ApplicationRecord
  enum kind: [ :appetizer, :soup, :main, :sweet ]
  
  validates :title, presence: true, uniqueness: true
  validates :kind, :price, presence: true

  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :alergens
  has_and_belongs_to_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :date, presence: true

  has_and_belongs_to_many :meals
  has_many :reservations
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :meal
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :menu
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.where('date >= ?', DateTime.now).order(:date)
  end

  def show
    @meal_view = Meal.find(params[:id])
    @rating_avg = Rating.where(meal_id: params[:id]).average(:value)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def create
    @meal = Meal.new(meal_params)
   
    if @meal.save
      params[:meal][:alergen_ids].each do |alergen_id|
        if !alergen_id.empty?
          @meal.alergens << Alergen.find(alergen_id)
        end
      end
      redirect_to @meal
    else
      render 'new'
    end
  end

  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      alergens = []
      params[:meal][:alergen_ids].each do |alergen_id|
        if !alergen_id.empty?
          alergens << Alergen.find(alergen_id)
        end
      end
      @meal.alergens = alergens
      redirect_to @meal
    else
      render 'edit'
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    redirect_to meals_path
  end

  private
    def meal_params
      params.require(:meal).permit(:title, :kind, :price)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      if !params[:menu][:appetizer_id].empty?
        @menu.meals << Meal.find(params[:menu][:appetizer_id])
      end
      if !params[:menu][:soup_id].empty?
        @menu.meals << Meal.find(params[:menu][:soup_id])
      end
      if !params[:menu][:main_id].empty?
        @menu.meals << Meal.find(params[:menu][:main_id])
      end
      if !params[:menu][:sweet_id].empty?
        @menu.meals << Meal.find(params[:menu][:sweet_id])
      end
      redirect_to @menu
    else
      render 'new'
    end
  end

  def update
    @menu = Menu.find(params[:id])

    if @menu.update(menu_params)
      redirect_to @menu
    else
      render 'edit'
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    redirect_to menus_path
  end

  private
    def menu_params
      params.require(:menu).permit(:date)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @rate_exists = Rating.where(meal_id: rating_params[:meal_id], ip_address: request.remote_ip)
    if @rate_exists.length > 0
      render json: { error: 'Already voted for this meal' }, status: 401
    else
      @rating = Rating.new({ value: rating_params[:value], ip_address: request.remote_ip, meal_id: rating_params[:meal_id] })
      @rating.save!
    end
  end

  private
    def rating_params
      params.require(:rating).permit(:value, :meal_id)
    end
end

app/helpers/alergens_helper.rb
module AlergensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/meals/_form.html.erb
<%= form_with model: @meal, local: true do |form| %>
  <% if @meal.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@meal.errors.count, "error") %>
        prohibited this article from being saved:
      </h4>
      <ul>
        <% @meal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Title</label>
    <%= form.text_field :title, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <label>Type</label>
    <%= form.select :kind, [['appetizer', :appetizer], ['soup', :soup], ['main dish', :main], ['sweet', :sweet]], {}, { :class => 'form-control'} %>
  </div>

  <div class="form-group">
    <label>Price</label>
    <%= form.number_field :price, in: 1..300, step: 1, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <label>Allergens</label>
    <%= form.select :alergen_ids,
                    options_from_collection_for_select(Alergen.order(:identifier).pluck(:id, :name), :first, :last, @meal.alergen_ids),
                    { },
                    { :multiple => true, :class => 'form-control' } %>
  </div>

  <div class="form-group">
    <%= link_to 'Back', meals_path, :class => 'btn btn-warning' %>
    <%= form.submit 'Submit', :class => 'btn btn-primary float-right' %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Edit Meal</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1 class="float-left">Listing meals</h1>
      <%= link_to 'New meal', new_meal_path, :class => 'btn btn-primary float-right' %>
    </div>
    <div class="col-10">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Type</th>
            <th>Price</th>
            <th>Allergens</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <% @meals.each do |meal| %>
          <tr>
            <td><%= meal.title %></td>
            <td>
              <% if meal.kind == 'main' %>
                main dish
              <% else %>
                <%= meal.kind %>
              <% end %>
            </td>
            <td><%= meal.price %></td>
            <td><%= meal.alergens.map(&:identifier).join(', ') %></td>
            <td>
              <%= link_to 'Show', meal_path(meal), :class => 'btn btn-primary' %>
              <%= link_to 'Edit', edit_meal_path(meal), :class => 'btn btn-warning' %>
              <%= link_to 'Delete', meal_path(meal), :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/meals/new.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>New Meal</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>
        Meal: <%= @meal.title %>
      </h1>

      <p>
        <strong>Type:</strong>
        <% if @meal.kind == 'main' %>
          main dish
        <% else %>
          <%= @meal.kind %>
        <% end %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @meal.price %>
      </p>

      <p>
        <strong>Allergens:</strong>
        <%= @meal.alergens.map(&:name).join(', ') %>
      </p>

      <%= link_to 'Back', meals_path, :class => 'btn btn-warning' %>
    </div>
  </div>
</div>

app/views/meals/user_show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>
        Meal: <%= @meal.title %>
      </h1>

      <p>
        <strong>Type:</strong>
        <% if @meal.kind == 'main' %>
          main dish
        <% else %>
          <%= @meal.kind %>
        <% end %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @meal.price %>
      </p>

      <p>
        <strong>Allergens:</strong>
        <%= @meal.alergens.map(&:name).join(', ') %>
      </p>

      <%= link_to 'Back', meals_path, :class => 'btn btn-warning' %>
    </div>
  </div>
</div>

app/views/menus/_form.html.erb
<%= form_with model: @menu, local: true do |form| %>
  <% if @menu.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@menu.errors.count, "error") %>
        prohibited this article from being saved:
      </h4>
      <ul>
        <% @menu.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Date</label>
    <div class="input-group date" id="datepicker" data-target-input="nearest">
      <%= form.text_field :date, :class => 'form-control datetimepicker-input', data: { target: '#datepicker' } %>
      <div class="input-group-append" data-target="#datepicker" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label>Appetizer</label>
    <%= form.select :appetizer_id,
                    options_from_collection_for_select(Meal.where(kind: :appetizer).order(:title).pluck(:id, :title), :first, :last, @menu.meal_ids),
                    { :prompt => 'select appetizer' },
                    { :class => 'form-control' } %>
  </div>    

  <div class="form-group">
    <label>Soup</label>
    <%= form.select :soup_id,
                    options_from_collection_for_select(Meal.where(kind: :soup).order(:title).pluck(:id, :title), :first, :last, @menu.meal_ids),
                    { :prompt => 'select soup' },
                    { :class => 'form-control' } %>
  </div>

  <div class="form-group">
    <label>Main meal</label>
    <%= form.select :main_id,
                    options_from_collection_for_select(Meal.where(kind: :main).order(:title).pluck(:id, :title), :first, :last, @menu.meal_ids),
                    { :prompt => 'select main meal' },
                    { :class => 'form-control' } %>
  </div>

  <div class="form-group">
    <label>Sweet</label>
    <%= form.select :sweet_id,
                    options_from_collection_for_select(Meal.where(kind: :sweet).order(:title).pluck(:id, :title), :first, :last, @menu.meal_ids),
                    { :prompt => 'select sweet' },
                    { :class => 'form-control' } %>
  </div>   

  <div class="form-group">
    <%= link_to 'Back', menus_path, :class => 'btn btn-warning' %>
    <%= form.submit 'Submit', :class => 'btn btn-primary float-right' %>
  </div>
<% end %>

<script>
  $(function() {
    $('#datepicker').datetimepicker({
      format: 'YYYY-MM-DD'
    });
  });
</script>

app/views/menus/edit.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Edit Menu</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="float-left">Listing menus</h1>
      <%= link_to 'New menu', new_menu_path, :class => 'btn btn-primary float-right' %>
    </div>
    <div class="col-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Meals</th>
            <th>Reservations</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <% @menus.each do |menu| %>
          <tr>
            <td><%= menu.date %></td>
            <td><%= menu.meals.map(&:title).join(', ') %></td>
            <td><%= menu.reservations.length %></td>
            <td>
              <%= link_to 'Reservations', menu_path(menu), :class => 'btn btn-primary' %>
              <%= link_to 'Edit', edit_menu_path(menu), :class => 'btn btn-warning' %>
              <%= link_to 'Delete', menu_path(menu), :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/menus/new.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>New Menu</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<%= render 'admin/nav.html.erb' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>
        Menu date: <%= @menu.date %>
      </h1>

      <ul>
        <li>
          <strong>Appetizer:</strong>
          <% @menu.meals.each do |meal| %>
            <% if meal.kind == 'appetizer' %>
              <span><%= meal.title %></span>
            <% end %>
          <% end %>
        </li>

        <li>
          <strong>Soup:</strong>
          <% @menu.meals.each do |meal| %>
            <% if meal.kind == 'soup' %>
              <span><%= meal.title %></span>
            <% end %>
          <% end %>
        </li>

        <li>
          <strong>Main meal:</strong>
          <% @menu.meals.each do |meal| %>
            <% if meal.kind == 'main' %>
              <span><%= meal.title %></span>
            <% end %>
          <% end %>
        </li>

        <li>
          <strong>Sweet:</strong>
          <% @menu.meals.each do |meal| %>
            <% if meal.kind == 'sweet' %>
              <span><%= meal.title %></span>
            <% end %>
          <% end %>
        </li>
      </ul>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Count</th>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
        <% @menu.reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.count %></td>
            <td><%= reservation.customer.name %> <%= reservation.customer.surname %></td>
            <td><%= reservation.customer.email %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <%= link_to 'Back', menus_path, :class => 'btn btn-warning' %>
    </div>
  </div>
</div>